Charge:
  actAs: [Timestampable]
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    vehicle_id: {type: integer, notnull: true }
    user_id: {type: integer, notnull: true }
    category_id: { type: integer, notnull: true }
    date: {type: date, notnull: true }
    kilometers:  { type: double , notnull: true }
    amount: { type: double, notnull: true}
    comment: clob
    quantity: { type: double }
  relations:
    Vehicle:
      local: vehicle_id
      onDelete: CASCADE
      foreignAlias: Charges
    Category:
      local: category_id
      onDelete: CASCADE
      foreignAlias: Charges
    User:
      class: sfGuardUser
      local: user_id
      onDelete: CASCADE
      foreignAlias: Charges
     
     
Category:
  actAs: [Timestampable, Sluggable]
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    name: { type: string(50), notnull: true, unique: true }
    comment: { type: clob }
    
    
Vehicle:
  actAs: [Timestampable, Sluggable]
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    name: { type: string(50), notnull: true }
    user_id: {type: integer, notnull: true }
    is_archived: {type: boolean, default: false }
  relations:
    User:
      class: sfGuardUser
      local: user_id
      onDelete: CASCADE
      foreignAlias: Vehicles


sfGuardUser:
  columns:
    list_max_per_page:
      type: string(5)
    api_key: 
      type: string(10)

Chart:
  actAs:
    Timestampable:
    Sluggable:
      name:   slug
      unique: true
      canUpdate: true
      indexName:  hashable
      type:   string
      length: 128
      fields: [vehicle_display, user_id, category_display, date_from, date_to, kilometers_from, kilometers_to, range_type, format, chart_name, Vehicles, Categories]
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    vehicle_display: {type: string(20) }
    user_id: {type: integer, notnull: true }
    category_display: {type: string(20)}
    date_from: {type: date }
    date_to: {type: date }
    kilometers_from:  { type: double }
    kilometers_to:  { type: double }
    range_type: {type: string(20)}
    format: {type: string(5)}
    chart_name: {type: string(40)}

  relations:
    Vehicles:
      onDelete: CASCADE
      foreignAlias: Charts
      class: Vehicle
      refClass: ChartVehicle
    Categories:
      onDelete: CASCADE
      foreignAlias: Charts
      class: Category
      refClass: ChartCategory
    User:
      class: sfGuardUser
      local: user_id
      onDelete: CASCADE
      foreignAlias: Charts

ChartVehicle:
  columns:
    chart_id:
      type: integer
      primary: true
    vehicle_id:
      type: integer
      primary: true
  relations:
    Chart:
      foreignAlias: ChartVehicles
      onDelete: CASCADE
    Vehicle:
      foreignAlias: ChartVehicles
      onDelete: CASCADE

ChartCategory:
  columns:
    chart_id:
      type: integer
      primary: true
    category_id:
      type: integer
      primary: true
  relations:
    Chart:
      foreignAlias: ChartVehicles
      onDelete: CASCADE
    Category:
      foreignAlias: ChartVehicles
      onDelete: CASCADE

Report:
  actAs:
    Timestampable:
    Sluggable: 
      name: 	slug
      unique: 	true
      canUpdate: 	false
      indexName: 	sluggable

  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    user_id: {type: integer, notnull: true}
    name: {type: varchar, notnull: true}
    date_from: {type: date }
    date_to: {type: date }
    kilometers_from:  { type: double }
    kilometers_to:  { type: double }
    is_new: {type: bool, notnull: true, default: true}
    num_vehicles: {type: integer, notnull: true}

  relations:
    Vehicles:
      onDelete: CASCADE
      foreignAlias: Reports
      class: Vehicle
      refClass: ReportVehicle
    User:
      class: sfGuardUser
      local: user_id
      onDelete: CASCADE
      foreignAlias: Reports

ReportVehicle:
  columns:
    report_id:
      type: integer
      primary: true
    vehicle_id:
      type: integer
      primary: true
  relations:
    Report:
      foreignAlias: ReportVehicles
      onDelete: CASCADE
    Vehicle:
      foreignAlias: ReportVehicles
      onDelete: CASCADE