charge:
  actAs: [Timestampable]
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    vehicle_id: integer
    date: {type: date, notnull: true }
    kilometers:  { type: double , notnull: true }
    category_id: { type: integer, notnull: true }
    amount: { type: double, notnull: true}
    comment: clob
    quantity: { type: double }
  relations:
    User:
      class: sfGuardUser
      local: id
      foreign: user_id
      foreignAlias: Charges
      foreignType: many
      type: one
     
     
category:
  actAs: [Timestampable, Sluggable]
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    name: { type: string(50), notnull: true }
    comment: { type: clob }
    
    
vehicle:
  actAs: [Timestampable, Sluggable]
  columns:
    id: { type: integer, notnull: true, primary: true, autoincrement: true }
    name: { type: string(50), notnull: true }
  relations:
    User:
      class: sfGuardUser
      local: id
      foreign: user_id
      foreignAlias: Vehicles
      foreignType: many
      type: one