# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sfApplyPlugin:
    from:
      email: "raffaele.bolliger@gmail.com"
      fullname: "The staff at otokou"

  sf_guard_plugin:
    #success_signin_url:      @my_route?param=value # the plugin use the referer as default
    success_signout_url:     homepage/index         # the plugin use the referer as default

  list:
    nb_links: 5;

  charts:
    force_generate: false    # force generation of charts at each request
    base_path: charts

  report:
    dir_name:  pdf
    force_generate: false
    max_on_index: 3
    max_on_list: 20

dev:
  charts:
    force_generate: true
  report:
    force_generate: true

test:
  charts:
    force_generate: true
    base_path: /functional/charts
  report:
    dir_name:  functional/pdf
    force_generate: true