# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  sfApplyPlugin:
    from:
      email: "raffaele.bolliger@gmail.com"
      fullname: "The staff at otokou"

  sf_guard_plugin:
    #success_signin_url:      @my_route?param=value # the plugin use the referer as default
    success_signout_url:     homepage/index         # the plugin use the referer as default
