graph_index:
  url: /:username/charts
  class: otkWithUserRoute
  param: {module: graphs, action: index }
  requirements:
    sf_method: [ get, post, head ]

graph_filter:
  url: /:username/charts/filter
  class: otkWithUserRoute
  param: {module: graphs, action: filter }
  requirements:
    sf_method: [post]

graph_cost_per_km:
  url: /:username/charts/cost_per_km
  class: otkWithUserRoute
  param: {module: graphs, action: costPerKm }
  requirements:
    sf_method: [ get ]

graph_cost_per_year:
  url: /:username/charts/cost_annual
  class: otkWithUserRoute
  param: {module: graphs, action: costPerYear }
  requirements:
    sf_method: [ get ]

graph_cost_allocation:
  url: /:username/charts/cost_allocation
  class: otkWithUserRoute
  param: {module: graphs, action: costPie }
  requirements:
    sf_method: [ get ]


vehicle:
  class: sfDoctrineRouteCollection
  options:
    model:                Vehicle
    module:               vehicle
    prefix_path:          /:username/settings/vehicles
    column:               id
    with_wildcard_routes: true
    route_class:          otkWithUserDoctrineRoute
    model_methods:
       list:              getAllByUser


charge:
  class: sfDoctrineRouteCollection
  options:
    model:                Charge
    module:               charge
    prefix_path:          /:username/charge
    column:               id
    with_wildcard_routes: true
    route_class:          otkWithUserDoctrineRoute
    model_methods:
       list:              getAllByUser

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

    
homepage_welcome:
  url:   /welcome
  param: {module: homepage, action: welcome }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
  
sf_guard_register:
  url:  /apply
  param: { module: sfApply, action: apply }

sf_guard_forgot_password:
  url: /reset-request
  param: { module: sfApply, action: resetRequest }
  
apply_reset:
  url: /reset
  param: { module: sfApply, action: reset }
  
apply_resetCancel:
  url: /reset-cancel
  param: { module: sfApply, action: resetCancel }


validate:
  url: /confirm/:validate
  param: { module: sfApply, action: confirm }


## User Settings
#------------------------------

user_settings_account:
  url: /:username/settings/account
  param: {module: user_settings, action: account}
  class: otkWithUserDoctrineRoute
  options:
    model: sfGuardUser
    type: object
    allow_empty: false
  requirements:
    sf_method: [get,post,put]
  
user_settings_otokou:
  url: /:username/settings/otokou
  param: {module: user_settings, action: otokou}
  class: otkWithUserDoctrineRoute
  options:
    model: sfGuardUser
    type: object
    allow_empty: false
  requirements:
    sf_method: [get,post,put]


# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
