chart_index:
  url: /:username/charts
  class: otkWithUserRoute
  param: {module: charts, action: index }
  requirements:
    sf_method: [ get, post, head ]

chart_filter:
  url: /:username/charts/filter
  class: otkWithUserRoute
  param: {module: charts, action: filter }
  requirements:
    sf_method: [post]

chart_cost_per_km:
  url: /:username/charts/cost_per_km
  class: otkWithUserRoute
  param: {module: charts, action: costPerKm }
  requirements:
    sf_method: [ get ]

chart_cost_per_year:
  url: /:username/charts/cost_annual
  class: otkWithUserRoute
  param: {module: charts, action: costPerYear }
  requirements:
    sf_method: [ get ]

chart_cost_allocation:
  url: /:username/charts/cost_allocation
  class: otkWithUserRoute
  param: {module: charts, action: costPie }
  requirements:
    sf_method: [ get ]

chart_trip_annual:
  url: /:username/charts/travel_annual
  class: otkWithUserRoute
  param: {module: charts, action: tripAnnual }
  requirements:
    sf_method: [ get ]

chart_trip_monthly:
  url: /:username/charts/travel_monthly
  class: otkWithUserRoute
  param: {module: charts, action: tripMonthly }
  requirements:
    sf_method: [ get ]

chart_consumption_per_distance:
  url: /:username/charts/consumption/per100km
  class: otkWithUserRoute
  param: {module: charts, action: consumptionPerDistance }
  requirements:
    sf_method: [ get ]


vehicle:
  class: sfDoctrineRouteCollection
  options:
    model:                Vehicle
    module:               vehicle
    prefix_path:          /:username/settings/vehicles
    column:               id
    with_wildcard_routes: true
    route_class:          otkWithUserDoctrineRoute
    model_methods:
       list:              getAllByUser


charge:
  class: sfDoctrineRouteCollection
  options:
    model:                Charge
    module:               charge
    prefix_path:          /:username/charge
    column:               id
    with_wildcard_routes: true
    route_class:          otkWithUserDoctrineRoute
    model_methods:
       list:              getAllByUser


report_index:
  class: otkWithUserDoctrineRoute
  url: /:username/reports
  param: {module: report, action: index }
  requirements:
    sf_method: get
  options:
    model:      Report
    type:       list
    method:     findNewByUser

reports_list_vehicle:
  class: otkWithUserDoctrineRoute
  url: /:username/reports/vehicle/:slug
  param: {module: report, action: listVehicle }
  requirements:
    sf_method: get
  options:
    model:      Report
    type:       list
    method:     findByUserAndVehicleSlug

reports_list_custom:
  class: otkWithUserDoctrineRoute
  url: /:username/reports/custom
  param: {module: report, action: listCustom }
  requirements:
    sf_method: get
  options:
    model:      Report
    type:       list
    method:     findCustomReportsByUser

report_show:
  class: otkWithUserDoctrineRoute
  url: /:username/report/show/:slug
  param: {module: report, action: show }
  requirements:
    sf_method: get
  options:
    model:      Report
    type:       object

report_delete:
  class: otkWithUserDoctrineRoute
  url: /:username/report/delete/:slug
  param: {module: report, action: delete }
  requirements:
    sf_method:  delete
  options:
    model:      Report
    type:       object

report_pdf:
  class: otkWithUserDoctrineRoute
  url: /:username/report/pdf/:slug
  param: {module: report, action: pdf }
  requirements:
    sf_method: get
  options:
    model:      Report
    type:       object

report_new:
  class: otkWithUserRoute
  url: /:username/report/new
  param: {module: report, action: new }
  requirements:
    sf_method: get

report_create:
  class: otkWithUserRoute
  url: /:username/report/create
  param: {module: report, action: create }
  requirements:
    sf_method: post


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

    
homepage_welcome:
  url:   /welcome
  param: {module: homepage, action: welcome }
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
  
sf_guard_register:
  url:  /apply
  param: { module: sfApply, action: apply }

sf_guard_forgot_password:
  url: /reset-request
  param: { module: sfApply, action: resetRequest }
  
apply_reset:
  url: /reset
  param: { module: sfApply, action: reset }
  
apply_resetCancel:
  url: /reset-cancel
  param: { module: sfApply, action: resetCancel }


validate:
  url: /confirm/:validate
  param: { module: sfApply, action: confirm }


## User Settings
#------------------------------

user_settings_account:
  url: /:username/settings/account
  param: {module: user_settings, action: account}
  class: otkWithUserDoctrineRoute
  options:
    model: sfGuardUser
    type: object
    allow_empty: false
  requirements:
    sf_method: [get,post,put]
  
user_settings_otokou:
  url: /:username/settings/otokou
  param: {module: user_settings, action: otokou}
  class: otkWithUserDoctrineRoute
  options:
    model: sfGuardUser
    type: object
    allow_empty: false
  requirements:
    sf_method: [get,post,put]


# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
