# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Otokou
    description:  A tool to track vehicle expenses
    keywords:     otokou, vehicle, cost, statistics, charts
    #language:     en
    robots:       index, follow
    viewport:     width=device-width, initial-scale=1.0


  #stylesheets:    [main.css]
  stylesheets:    [foundation/globals.css, foundation/grid.css, foundation/typography.css, foundation/ui.css, foundation/mobile.css, main.css, menus.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
