<?php

/**
 * BaseChartCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $chart_id
 * @property integer $category_id
 * @property Chart $Chart
 * @property Category $Category
 * 
 * @method integer       getChartId()     Returns the current record's "chart_id" value
 * @method integer       getCategoryId()  Returns the current record's "category_id" value
 * @method Chart         getChart()       Returns the current record's "Chart" value
 * @method Category      getCategory()    Returns the current record's "Category" value
 * @method ChartCategory setChartId()     Sets the current record's "chart_id" value
 * @method ChartCategory setCategoryId()  Sets the current record's "category_id" value
 * @method ChartCategory setChart()       Sets the current record's "Chart" value
 * @method ChartCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChartCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chart_category');
        $this->hasColumn('chart_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Chart', array(
             'local' => 'chart_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}