<?php

/**
 * BaseGraphVehicle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $graph_id
 * @property integer $vehicle_id
 * @property Graph $Graph
 * @property Vehicle $Vehicle
 * 
 * @method integer      getGraphId()    Returns the current record's "graph_id" value
 * @method integer      getVehicleId()  Returns the current record's "vehicle_id" value
 * @method Graph        getGraph()      Returns the current record's "Graph" value
 * @method Vehicle      getVehicle()    Returns the current record's "Vehicle" value
 * @method GraphVehicle setGraphId()    Sets the current record's "graph_id" value
 * @method GraphVehicle setVehicleId()  Sets the current record's "vehicle_id" value
 * @method GraphVehicle setGraph()      Sets the current record's "Graph" value
 * @method GraphVehicle setVehicle()    Sets the current record's "Vehicle" value
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGraphVehicle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('graph_vehicle');
        $this->hasColumn('graph_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('vehicle_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Graph', array(
             'local' => 'graph_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Vehicle', array(
             'local' => 'vehicle_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}