<?php

/**
 * Basecategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property clob $comment
 * 
 * @method integer  getId()      Returns the current record's "id" value
 * @method string   getName()    Returns the current record's "name" value
 * @method clob     getComment() Returns the current record's "comment" value
 * @method category setId()      Sets the current record's "id" value
 * @method category setName()    Sets the current record's "name" value
 * @method category setComment() Sets the current record's "comment" value
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('comment', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}