<?php

/**
 * Basevehicle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property sfGuardUser $User
 * 
 * @method integer     getId()   Returns the current record's "id" value
 * @method string      getName() Returns the current record's "name" value
 * @method sfGuardUser getUser() Returns the current record's "User" value
 * @method vehicle     setId()   Sets the current record's "id" value
 * @method vehicle     setName() Sets the current record's "name" value
 * @method vehicle     setUser() Sets the current record's "User" value
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basevehicle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vehicle');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}