<?php

/**
 * BaseGraphCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $graph_id
 * @property integer $category_id
 * @property Graph $Graph
 * @property Category $Category
 * 
 * @method integer       getGraphId()     Returns the current record's "graph_id" value
 * @method integer       getCategoryId()  Returns the current record's "category_id" value
 * @method Graph         getGraph()       Returns the current record's "Graph" value
 * @method Category      getCategory()    Returns the current record's "Category" value
 * @method GraphCategory setGraphId()     Sets the current record's "graph_id" value
 * @method GraphCategory setCategoryId()  Sets the current record's "category_id" value
 * @method GraphCategory setGraph()       Sets the current record's "Graph" value
 * @method GraphCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGraphCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('graph_category');
        $this->hasColumn('graph_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Graph', array(
             'local' => 'graph_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}