<?php

/**
 * BaseChartVehicle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $chart_id
 * @property integer $vehicle_id
 * @property Chart $Chart
 * @property Vehicle $Vehicle
 * 
 * @method integer      getChartId()    Returns the current record's "chart_id" value
 * @method integer      getVehicleId()  Returns the current record's "vehicle_id" value
 * @method Chart        getChart()      Returns the current record's "Chart" value
 * @method Vehicle      getVehicle()    Returns the current record's "Vehicle" value
 * @method ChartVehicle setChartId()    Sets the current record's "chart_id" value
 * @method ChartVehicle setVehicleId()  Sets the current record's "vehicle_id" value
 * @method ChartVehicle setChart()      Sets the current record's "Chart" value
 * @method ChartVehicle setVehicle()    Sets the current record's "Vehicle" value
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChartVehicle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chart_vehicle');
        $this->hasColumn('chart_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('vehicle_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Chart', array(
             'local' => 'chart_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Vehicle', array(
             'local' => 'vehicle_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}