<?php

/**
 * Basecharge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $vehicle_id
 * @property date $date
 * @property double $kilometers
 * @property integer $category_id
 * @property double $amount
 * @property clob $comment
 * @property double $quantity
 * @property sfGuardUser $User
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getVehicleId()   Returns the current record's "vehicle_id" value
 * @method date        getDate()        Returns the current record's "date" value
 * @method double      getKilometers()  Returns the current record's "kilometers" value
 * @method integer     getCategoryId()  Returns the current record's "category_id" value
 * @method double      getAmount()      Returns the current record's "amount" value
 * @method clob        getComment()     Returns the current record's "comment" value
 * @method double      getQuantity()    Returns the current record's "quantity" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method charge      setId()          Sets the current record's "id" value
 * @method charge      setVehicleId()   Sets the current record's "vehicle_id" value
 * @method charge      setDate()        Sets the current record's "date" value
 * @method charge      setKilometers()  Sets the current record's "kilometers" value
 * @method charge      setCategoryId()  Sets the current record's "category_id" value
 * @method charge      setAmount()      Sets the current record's "amount" value
 * @method charge      setComment()     Sets the current record's "comment" value
 * @method charge      setQuantity()    Sets the current record's "quantity" value
 * @method charge      setUser()        Sets the current record's "User" value
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecharge extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('charge');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('vehicle_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('kilometers', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('amount', 'double', null, array(
             'type' => 'double',
             'notnull' => true,
             ));
        $this->hasColumn('comment', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('quantity', 'double', null, array(
             'type' => 'double',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}