<?php

/**
 * categoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class categoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object categoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('category');
    }
}