<?php

/**
 * ChargeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChargeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ChargeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Charge');
    }

    public static function getAllByUser($user_id) {

        return $this->createQuery('c')
                ->where('c.user_id = ?', $user_id)
                ->execute();
    }

    public function retrieveAdminChargeList(Doctrine_Query $q) {
        $rootAlias = $q->getRootAlias();

        $q->leftJoin($rootAlias . '.Category ct');
        $q->leftJoin($rootAlias . '.Vehicle v');
        $q->andWhere('v.is_archived = ?', false);

        return $q;
    }

    public function getAllByUserAndVehiclesQuery($user_id, $vehicles_ids = array()) {

        $q = $this->createQuery('c')
                ->addWhere('c.user_id = ?', $user_id);

        if ($vehicles_ids) {

            $q->leftJoin('c.Vehicle v')
                    ->andWhereIn('v.id', $vehicles_ids);
        }

        return $q;
    }

    public function addRangeQuery($q = null, $values = array()) {

        if (null === $q) {
            $q = $this->createQuery('c');
        }

        $alias = $q->getRootAlias();

        if (isset($values['date_from']) && null !== $values['date_from']) {
            $q->addWhere($alias . '.date >= ?', $values['date_from']);
        }

        if (isset($values['date_to']) && null !== $values['date_to']) {
            $q->addWhere($alias . '.date < ?', $values['date_to']);
        }

        if (isset($values['kilometers_from']) && null !== $values['kilometers_from']) {
            $q->addWhere($alias . '.kilometers >= ?', $values['kilometers_from']);
        }

        if (isset($values['kilometers_to']) && null !== $values['kilometers_to']) {
            $q->addWhere($alias . '.kilometers < ?', $values['kilometers_to']);
        }

        return $q;
    }

}