<?php

/**
 * Chart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Chart extends BaseChart {

    public function preSave($event) {
        parent::preSave($event);


        if (!$this->getSha()) {

            $sha = $this->generateSha();
            while (true) {
                $g = Doctrine_Core::getTable('Chart')->findOneBySha($sha);
                if (empty($g)) {
                    break;
                }
                $sha = $this->generateSha(true, array('with_random_string' => true));
            }


            $this->setSha($sha);
        }
    }

    public function generateSha($force = false, $options = array()) {

        if ($this->getSha() && !$force) {
            return;
        }

// getting table columns
        $columns = $this->getTable()->getColumnNames();

// getting relations Ids
        $relations_ids = array();
        foreach ($this->getReferences() as $relation) {

            foreach ($relation as $element) {

                $relations_ids[get_class($element)][] = $element->getId();
            }
        }


// building hash string
        $str = '';
        $sep = ', ';
        foreach ($columns as $col) {
            $cnt = $this->get($col);

            if (empty($cnt)) {
                continue;
            }

            $str .= implode($sep, (array) $cnt);
        }

        if ($relations_ids) {
            foreach ($relations_ids as $name => $value) {

                $str .= implode($sep, (array) $value);
            }
        }

        if (isset($options['with_random_string'])) {
            $str .= $this->generateRandomString(20);
        }

        return sha1($str);
    }

    protected function generateRandomString($length = 32, $chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890') {

        // Length of character list
        $chars_length = (strlen($chars) - 1);

        // Start our string
        $string = $chars{rand(0, $chars_length)};

        // Generate random string
        for ($i = 1; $i < $length; $i = strlen($string)) {
            // Grab a random character from our list
            $string .= $chars{rand(0, $chars_length)};
        }

        // Return the string
        return $string;
    }

    public function getChartPath($type = 'web') {

        return $this->getChartBasePath($type) . '/' . $this->getChartName();
    }

    public function getChartName() {
        return $this->getSha() . '.' . $this->getChartFormat();
    }

    public function getChartFormat() {

        $format = $this->getFormat();

        $format = (!$format || is_null($format)) ?
                sfConfig::get('app_chart_default_format', 'png') :
                $format;

        return $format;
    }

    public function getChartBasePath($type = 'web') {

        $path = sfConfig::get('app_chart_base_path', '/charts');


        switch ($type) {
            case 'web':
                $path = ($path[0] == '/' ? substr($path, 1) : $path);

                break;

            case 'system':
                $path = ($path[0] == '/' ? $path : '/' . $path);

                // adding "images" folder
                $path = '/' . sfConfig::get('sf_web_images_dir_name', 'images') . $path;

                $path = $this->convertToSystemPath($path);

                $path = sfConfig::get('sf_web_dir') . $path;


                break;

            default:

                throw new sfException('Unknown option ' . $type);
        }

        return $path;
    }

    protected function convertToSystemPath($path) {

        return str_replace("/", DIRECTORY_SEPARATOR, $path);
    }

    public function delete(Doctrine_Connection $conn = null) {

        parent::delete($conn);

        $path = $this->getChartPath('system');

        if (file_exists($path)) {
            $fs = new sfFilesystem(new sfEventDispatcher());
            $fs->remove($path);
        }
    }

}
