<?php

/**
 * ChargeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChargeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChargeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Charge');
    }
    
    public static function getAllByUser($user_id)
    {
        
        sfContext::getInstance()->getLogger()->info('sdgsdfgsfg');
        return $this->createQuery('c')
                ->where('c.user_id = ?',$user_id)
                ->execute();
    }
    

}