<?php

/**
 * ChartCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChartCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChartCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChartCategory');
    }
}