<?php

/**
 * ChargeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChargeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChargeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Charge');
    }
    
    public static function getAllByUser($user_id)
    {
        
        return $this->createQuery('c')
                ->where('c.user_id = ?',$user_id)
                ->execute();
    }
    
    public function retrieveAdminChargeList(Doctrine_Query $q)
  {
    $rootAlias = $q->getRootAlias();
 
    $q->leftJoin($rootAlias . '.Category ct');
    $q->leftJoin($rootAlias . '.Vehicle v');
    $q->andWhere('v.is_archived = ?',false);
 
    return $q;
  }
  
  public function getAllByUserAndVehiclesQuery($user_id,$vehicles_ids) {
      
      return $this->createQuery('c')
              ->addWhere('c.user_id = ?',$user_id)
              ->leftJoin('c.Vehicle v')
              ->andWhereIn('v.id', $vehicles_ids);
  }

    

}