<?php

/**
 * chargeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class chargeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object chargeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('charge');
    }
}