<?php

/**
 * GraphVehicleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GraphVehicleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GraphVehicleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GraphVehicle');
    }
}