<?php

/**
 * GraphCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GraphCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GraphCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GraphCategory');
    }
}