<?php

/**
 * GraphTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GraphTable extends Doctrine_Table
{

    protected static $display_choices = array(
        'stacked' => 'Stacked',
        'single'  => 'Single'
    );


    protected static $range_type = array(
        'date' => 'Date',
        'distance' => 'Kilomenters',
    );

    /**
     * Returns an instance of this class.
     *
     * @return object GraphTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Graph');
    }

    public static function getDisplayChoices() {
        return self::$display_choices;
    }

    public static function getRangeTypes() {
        return self::$range_type;
    }
}