<?php

/**
 * Report
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Report extends BaseReport {

    public function preSave($event) {

        parent::preSave($event);

        $invoker = $event->getInvoker();

        $vehicles = $invoker->getVehicles();

        $invoker->setNumVehicles(count($vehicles));
    }

    public function isCustom() {

        return $this->getNumVehicles() > 1 ? true : false;
    }

     public function getHash() {
        return sha1($this->getSlug());
    }
    
    public function getPdfFileName() {
        
        return $this->getHash().'.pdf';  
    }
    
    public function getPdfWebPath() {
        return sfConfig::get('app_report_dir_name');
    }
    
    public function getPdfFileWebPath() {
        return $this->getPdfWebPath() . '/' . $this->getPdfFileName();
    }
    
    public function getPdfSystemPath() {
        return sfConfig::get('sf_web_dir') . DIRECTORY_SEPARATOR . str_replace('/', DIRECTORY_SEPARATOR, $this->getPdfWebPath());
    }
    
    public function getPdfFileFullPath() {
        return $this->getPdfSystemPath(). DIRECTORY_SEPARATOR .$this->getPdfFileName();
    }
    

}
