<?php

/**
 * ReportVehicleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportVehicleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportVehicleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReportVehicle');
    }
}