<?php

/**
 * ReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ReportTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Report');
    }

    public static function findNewByUser($params) {

        $username = $params['username'];

        $q = self::getInstance()->createQuery('r')
                ->andWhere('r.is_new = ?', true)
                ->orderBy('r.created_at ASC');

        $q = $this->addUsernameQuery($username, $q);


        return $q->execute();
    }

    public static function findByUserAndVehicleSlug($params) {

        $username = $params['username'];
        $vehicle_slug = $params['slug'];

        $q = self::getInstance()->createQuery('r')
                ->leftJoin('r.Vehicles v')
                ->andWhere('v.slug = ?', $vehicle_slug)
                ->andWhere('r.num_vehicles = ?', 1)
                ->orderBy('r.is_new DESC, r.created_at DESC');

        $q = self::getInstance()->addUsernameQuery($username, $q);


        if (isset($params['limit'])) {
            $q->limit($params['limit']);
        }

        return $q->execute();
    }

    public static function findCustomReportsByUser($params) {

        $q = self::getInstance()->getCustomReportsByUserQuery($params);

        return $q->execute();
    }

    public function getCustomReportsByUserQuery($params = array()) {

        $username = $params['username'];

        $q = self::getInstance()->createQuery('r')
                ->addSelect('r.*')
                ->andWhere('r.num_vehicles > ?', 1)
                ->orderBy('r.is_new DESC, r.created_at DESC');

        $q = self::getInstance()->addUsernameQuery($username, $q);


        // ensures that at least one vehicle is active
        $q = self::getInstance()->addCheckActiveQuery($q);



        if (isset($params['max'])) {
            $q->limit($max);
        }

        return $q;
    }

    public function addCheckActiveQuery($q) {

        $q->leftJoin('r.Vehicles v')
                ->addSelect('r.*, (r.num_vehicles) nv')
                ->groupBy('r.id')
                ->having('SUM(v.is_archived) < nv');

        return $q;
    }

    public function addUsernameQuery($username, Doctrine_Query $q = null) {

        if (is_null($q)) {
            $q = Doctrine_Query::create()
                    ->from('Report r');
        }


        $root = $q->getRootAlias();

        $q->leftJoin($root . '.User u')
                ->andWhere('u.username = ?', $username);

        return $q;
    }

    public function retrieveOrderedReport(Doctrine_Query $q) {
        return $this->addOrderedReportsQuery($q)->fetchOne();
    }

    public function getOrderedReports(Doctrine_Query $q = null) {
        return $this->addOrderedReportsQuery($q)->execute();
    }

    public function countReports(Doctrine_Query $q = null) {

        if (is_null($q)) {
            $q = Doctrine_Query::create()
                    ->from('Report r');
        }

        return $q->count();
    }

    public function countNewCustomReports($user_id) {

        $q = $this->createQuery('r')
                ->addWhere('r.user_id = ?', $user_id)
                ->addWhere('r.num_vehicles > ?', 1)
                ->addWhere('r.is_new = ?', true);

        $q = self::getInstance()->addCheckActiveQuery($q);
        
        return $q->count();
    }

    public function addOrderedReportsQuery(Doctrine_Query $q = null) {
        if (is_null($q)) {
            $q = Doctrine_Query::create()
                    ->from('Report r');
        }

        //$alias = $q->getRootAlias();

        $q->OrderBy('r.is_new DESC, r.created_at DESC');

        return $q;
    }

}