<?php

/**
 * ReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Report');
    }

    public static function findNewByUser($params) {

        $username = $params['username'];

        return self::getInstance()->createQuery('r')
                ->leftJoin('r.User u')
                ->andWhere('u.username = ?',$username)
                ->andWhere('r.is_new = ?',true)
                ->orderBy('r.created_at ASC')
                ->execute();
    }

    public static function findByUserAndVehicleSlug($params) {

        $username = $params['username'];
        $vehicle_slug = $params['slug'];

        return self::getInstance()->createQuery('r')
                ->leftJoin('r.User u')
                ->andWhere('u.username = ?',$username)
                ->leftJoin('r.Vehicles v')
                ->andWhere('v.slug = ?',$vehicle_slug)
                ->andWhere('r.num_vehicles = ?',1)
                ->orderBy('r.created_at ASC')
                ->execute();
    }

    public static function findCustomReportsByUser($params) {

        $username = $params['username'];

        return self::getInstance()->createQuery('r')
                ->leftJoin('r.User u')
                ->andWhere('u.username = ?',$username)
                ->andWhere('r.num_vehicles > ?',1)
                ->orderBy('r.created_at ASC')
                ->execute();
    }
}