<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
    
    public function getFullname() {
        $user = $this->getUser();
        
        $fullname =  $user->getFirstName().' '.$user->getLastName();
        
        return $fullname ? $fullname : null;
    }
    
    public function getEmail() {
               
        return $this->getUser()->getEmailAddress();
    }
}
