<?php

/**
 * vehicleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class vehicleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object vehicleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('vehicle');
    }
}