<?php

/**
 * Vehicle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    otokou
 * @subpackage model
 * @author     Raffaele Bolliger
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Vehicle extends BaseVehicle {

    public function toggleArchive() {
        $this->setIsArchived(!$this->getIsArchived());
        $this->save();
    }

    public function getTraveledDistance() {

        $charges = $this->getCharges();

        if (!count($charges)) {
            return 0;
        }

        $dist = array();
        foreach ($charges as $c) {
            $dist[] = $c->getKilometers();
        }

        return max($dist);
    }

    public function getOverallCost() {

        $charges = $this->getCharges();

        if (!count($charges)) {
            return 0;
        }

        $cost = array();
        foreach ($charges as $c) {
            $cost[] = $c->getAmount();
        }

        return array_sum($cost);
    }

    public function getCostPerKm() {

        $cost = $this->getOverallCost();
        $dist = $this->getTraveledDistance();

        if ($dist == 0) {
            return null;
        }

        return $cost / $dist;
    }

    public function getAverageConsumption() {

        $charges = $this->getCharges();

        if (!count($charges)) {
            return null;
        }

        $dist = $this->getTraveledDistance();

        $fuelId = Doctrine_Core::getTable('Category')->findOneByName('Fuel')->getId();

        $quantity = array();
        foreach ($charges as $c) {

            if ($fuelId === $c->getCategoryId()) {
                $quantity[] = $c->getQuantity();
            }
        }

        if (!count($quantity)) {
            return null;
        }

        return array_sum($quantity) / $dist * 100;
    }

}
