<?php

/**
 * VehicleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VehicleTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object VehicleTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Vehicle');
    }

    public function getVehiclesByUserIdQuery($id) {
        $q = $this->createQuery('v')->select('v.*')
                        ->andWhere('v.user_id = ?', $id);

        return $q;
    }

    public function findByUserIdAndVehicleId($user_id = array(), $vehicle_id = array()) {

        if (!$user_id) {
            throw new Doctrine_Table_Exception('You must specify a "user_id"');
        }

        $q = $this->createQuery('v')->andWhere('v.user_id = ?', $user_id);

        if ($vehicle_id) {
            $q->andWhereIn('v.id', $vehicle_id);
        }
        
        return $q->execute();
    }

}